### ISSUE TITLE
Screenshots in README

### ISSUE THREAD

**Issue by matthew-piziak** [reims/org-tvdb#2]
Would be nice to see it in action!

**Comment by reims** [comment]
Thanks for your feedback! I added a screenshot to the README.

I'm closing this for now. Just reopen it, if you think more screenshots would be helpful.

As a side note: I have to admit that I don't use org-tvdb myself. Somehow it never got to the point where it was really useful to me. So I'm thankful for any feature ideas that might make this useful to you.
